#!/usr/bin/env python3
"""Generate deterministic Operator Intelligence repository maps from the artifact registry."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "registry" / "artifacts.yaml"
OUTPUT_DIR = ROOT / "generated"


def load_registry() -> dict:
    return json.loads(REGISTRY.read_text(encoding="utf-8"))


def model(data: dict) -> dict:
    roots = sorted(data["governed_roots"], key=lambda item: item["path"])
    source_artifacts = sorted(data["artifacts"], key=lambda item: item["path"])
    artifacts = [
        {
            "artifact_id": artifact["artifact_id"],
            "path": artifact["path"],
            "artifact_type": artifact["artifact_type"],
            "authority_state": artifact["authority_state"],
            "release_scope": artifact["release_scope"],
            "status": artifact["status"],
        }
        for artifact in source_artifacts
    ]
    return {
        "schema_version": "oi-repository-map-v1",
        "source": "registry/artifacts.yaml",
        "governed_roots": roots,
        "artifacts": artifacts,
        "edges": sorted(
            [
                {"from": dependency, "to": artifact["path"], "type": "depends_on"}
                for artifact in source_artifacts
                for dependency in artifact.get("depends_on", [])
            ],
            key=lambda item: (item["from"], item["to"]),
        ),
    }


def markdown(data: dict) -> str:
    lines = [
        "# Operator Intelligence — Registry-Generated Repository Map",
        "",
        "Generated from `registry/artifacts.yaml`. Do not edit this file directly.",
        "",
        "## Governed roots",
        "",
        "| Path | Type | Authority | Release scope |",
        "|---|---|---|---|",
    ]
    for root in data["governed_roots"]:
        lines.append(f"| `{root['path']}/` | {root['artifact_type']} | `{root['authority_state']}` | {root['release_scope']} |")
    lines.extend(["", "## Explicit artifact authorities", "", "| ID | Path | Type | Authority | Status |", "|---|---|---|---|---|"])
    for artifact in data["artifacts"]:
        lines.append(f"| `{artifact['artifact_id']}` | `{artifact['path']}` | {artifact['artifact_type']} | `{artifact['authority_state']}` | {artifact['status']} |")
    lines.extend([
        "",
        "## Authority flow",
        "",
        "```text",
        "Root release authorities",
        "→ Governed folder roots",
        "→ Explicit canonical or extension artifacts",
        "→ Proposed and generated artifacts kept visibly separate",
        "→ Registry validation",
        "→ Reproducible repository map",
        "```",
        "",
    ])
    return "\n".join(lines)


def compact_json(data: dict) -> str:
    lines = ["{"]
    for key in ("artifacts", "edges", "governed_roots"):
        lines.append(f'  "{key}": [')
        values = data[key]
        for index, value in enumerate(values):
            suffix = "," if index < len(values) - 1 else ""
            lines.append("    " + json.dumps(value, sort_keys=True, separators=(",", ":")) + suffix)
        lines.append("  ],")
    lines.append('  "schema_version":' + json.dumps(data["schema_version"]) + ",")
    lines.append('  "source":' + json.dumps(data["source"]))
    lines.append("}")
    return "\n".join(lines) + "\n"


def mermaid(data: dict) -> str:
    lines = ["flowchart LR", '  registry["Artifact Registry"]']
    for index, root in enumerate(data["governed_roots"], start=1):
        node = f"root{index}"
        label = f"{root['path']}/\\n{root['authority_state']}"
        lines.append(f'  {node}["{label}"]')
        lines.append(f"  registry --> {node}")
    for index, artifact in enumerate(data["artifacts"], start=1):
        node = f"artifact{index}"
        label = f"{artifact['path']}\\n{artifact['authority_state']}"
        lines.append(f'  {node}["{label}"]')
        parent = next((i for i, root in enumerate(data["governed_roots"], start=1) if artifact["path"] == root["path"] or artifact["path"].startswith(root["path"] + "/")), None)
        lines.append(f"  {'root' + str(parent) if parent else 'registry'} --> {node}")
    return "\n".join(lines) + "\n"


def dot(data: dict) -> str:
    lines = ['digraph OperatorIntelligence {', '  rankdir="LR";', '  registry [label="Artifact Registry", shape=box];']
    for index, root in enumerate(data["governed_roots"], start=1):
        node = f"root{index}"
        lines.append(f'  {node} [label="{root["path"]}/\\n{root["authority_state"]}", shape=folder];')
        lines.append(f"  registry -> {node};")
    for index, artifact in enumerate(data["artifacts"], start=1):
        node = f"artifact{index}"
        lines.append(f'  {node} [label="{artifact["path"]}\\n{artifact["authority_state"]}", shape=note];')
        parent = next((i for i, root in enumerate(data["governed_roots"], start=1) if artifact["path"] == root["path"] or artifact["path"].startswith(root["path"] + "/")), None)
        lines.append(f"  {'root' + str(parent) if parent else 'registry'} -> {node};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def outputs(data: dict) -> dict[Path, str]:
    mapped = model(data)
    return {
        OUTPUT_DIR / "repository-map.md": markdown(mapped),
        OUTPUT_DIR / "repository-map.json": compact_json(mapped),
        OUTPUT_DIR / "repository-map.mmd": mermaid(mapped),
        OUTPUT_DIR / "repository-map.dot": dot(mapped),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated files are missing or stale")
    args = parser.parse_args()
    data = load_registry()
    expected = outputs(data)
    stale = []
    for path, content in expected.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print(json.dumps({"decision": "HALT", "stale_outputs": stale}, indent=2))
        return 1
    print(json.dumps({"decision": "ALLOW", "outputs": [path.relative_to(ROOT).as_posix() for path in expected]}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
